services:
  - type: worker
    name: watchbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MY_TELEGRAM_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_FILE
        value: credentials.json
